# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_Filtro_Frecuencia(object):
    def setupUi(self, Dialog_Filtro_Frecuencia):
        Dialog_Filtro_Frecuencia.setObjectName(_fromUtf8("Dialog_Filtro_Frecuencia"))
        Dialog_Filtro_Frecuencia.resize(271, 307)
        Dialog_Filtro_Frecuencia.setStyleSheet(_fromUtf8("#Dialog_Filtro_Frecuencia{\n"
"    background-color: rgb(227, 227, 227);\n"
"}"))
        self.tab_Preferencias = QtGui.QTabWidget(Dialog_Filtro_Frecuencia)
        self.tab_Preferencias.setGeometry(QtCore.QRect(10, 10, 251, 251))
        self.tab_Preferencias.setStyleSheet(_fromUtf8(""))
        self.tab_Preferencias.setObjectName(_fromUtf8("tab_Preferencias"))
        self.tab_FrecMuestreo = QtGui.QWidget()
        self.tab_FrecMuestreo.setObjectName(_fromUtf8("tab_FrecMuestreo"))
        self.groupBox_FrecCorte = QtGui.QGroupBox(self.tab_FrecMuestreo)
        self.groupBox_FrecCorte.setGeometry(QtCore.QRect(10, 70, 221, 51))
        font = QtGui.QFont()
        font.setKerning(True)
        self.groupBox_FrecCorte.setFont(font)
        self.groupBox_FrecCorte.setTitle(_fromUtf8(""))
        self.groupBox_FrecCorte.setObjectName(_fromUtf8("groupBox_FrecCorte"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_FrecCorte)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 178, 27))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_FrecCorte = QtGui.QLabel(self.layoutWidget)
        self.label_FrecCorte.setObjectName(_fromUtf8("label_FrecCorte"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_FrecCorte)
        self.comboBox_FrecFiltroON = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_FrecFiltroON.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_FrecFiltroON.setFont(font)
        self.comboBox_FrecFiltroON.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_FrecFiltroON.setAccessibleDescription(_fromUtf8(""))
        self.comboBox_FrecFiltroON.setAutoFillBackground(False)
        self.comboBox_FrecFiltroON.setInputMethodHints(QtCore.Qt.ImhNone)
        self.comboBox_FrecFiltroON.setEditable(False)
        self.comboBox_FrecFiltroON.setObjectName(_fromUtf8("comboBox_FrecFiltroON"))
        self.comboBox_FrecFiltroON.addItem(_fromUtf8(""))
        self.comboBox_FrecFiltroON.addItem(_fromUtf8(""))
        self.comboBox_FrecFiltroON.addItem(_fromUtf8(""))
        self.comboBox_FrecFiltroON.addItem(_fromUtf8(""))
        self.comboBox_FrecFiltroON.addItem(_fromUtf8(""))
        self.comboBox_FrecFiltroON.addItem(_fromUtf8(""))
        self.comboBox_FrecFiltroON.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox_FrecFiltroON)
        self.groupBox_Filtro = QtGui.QGroupBox(self.tab_FrecMuestreo)
        self.groupBox_Filtro.setGeometry(QtCore.QRect(10, 20, 221, 61))
        self.groupBox_Filtro.setObjectName(_fromUtf8("groupBox_Filtro"))
        self.widget = QtGui.QWidget(self.groupBox_Filtro)
        self.widget.setGeometry(QtCore.QRect(10, 20, 184, 22))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_FiltroPasaBaja = QtGui.QLabel(self.widget)
        self.label_FiltroPasaBaja.setObjectName(_fromUtf8("label_FiltroPasaBaja"))
        self.gridLayout.addWidget(self.label_FiltroPasaBaja, 0, 0, 1, 1)
        self.radioButton_filtroOn = QtGui.QRadioButton(self.widget)
        self.radioButton_filtroOn.setAcceptDrops(False)
        self.radioButton_filtroOn.setAutoFillBackground(False)
        self.radioButton_filtroOn.setChecked(True)
        self.radioButton_filtroOn.setObjectName(_fromUtf8("radioButton_filtroOn"))
        self.gridLayout.addWidget(self.radioButton_filtroOn, 0, 1, 1, 1)
        self.radioButton_filtroOff = QtGui.QRadioButton(self.widget)
        self.radioButton_filtroOff.setObjectName(_fromUtf8("radioButton_filtroOff"))
        self.gridLayout.addWidget(self.radioButton_filtroOff, 0, 2, 1, 1)
        self.groupBox_FrecMuestreo = QtGui.QGroupBox(self.tab_FrecMuestreo)
        self.groupBox_FrecMuestreo.setGeometry(QtCore.QRect(10, 120, 241, 101))
        self.groupBox_FrecMuestreo.setObjectName(_fromUtf8("groupBox_FrecMuestreo"))
        self.label = QtGui.QLabel(self.groupBox_FrecMuestreo)
        self.label.setGeometry(QtCore.QRect(30, 80, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.comboBox_FrecMuestreoOFF = QtGui.QComboBox(self.groupBox_FrecMuestreo)
        self.comboBox_FrecMuestreoOFF.setEnabled(True)
        self.comboBox_FrecMuestreoOFF.setGeometry(QtCore.QRect(120, 20, 61, 25))
        self.comboBox_FrecMuestreoOFF.setFrame(True)
        self.comboBox_FrecMuestreoOFF.setObjectName(_fromUtf8("comboBox_FrecMuestreoOFF"))
        self.comboBox_FrecMuestreoOFF.addItem(_fromUtf8(""))
        self.comboBox_FrecMuestreoOFF.addItem(_fromUtf8(""))
        self.comboBox_FrecMuestreoOFF.addItem(_fromUtf8(""))
        self.comboBox_FrecMuestreoOFF.addItem(_fromUtf8(""))
        self.comboBox_FrecMuestreoOFF.addItem(_fromUtf8(""))
        self.comboBox_FrecMuestreoOFF.addItem(_fromUtf8(""))
        self.comboBox_FrecMuestreoOFF.addItem(_fromUtf8(""))
        self.comboBox_FrecMuestreoOFF.addItem(_fromUtf8(""))
        self.comboBox_FrecMuestreoOFF.addItem(_fromUtf8(""))
        self.comboBox_FrecMuestreoOFF.addItem(_fromUtf8(""))
        self.label_2 = QtGui.QLabel(self.groupBox_FrecMuestreo)
        self.label_2.setGeometry(QtCore.QRect(190, 20, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_FrecMuestreo = QtGui.QLabel(self.groupBox_FrecMuestreo)
        self.label_FrecMuestreo.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.label_FrecMuestreo.setObjectName(_fromUtf8("label_FrecMuestreo"))
        self.comboBox_FrecMuestreoON = QtGui.QComboBox(self.groupBox_FrecMuestreo)
        self.comboBox_FrecMuestreoON.setEnabled(True)
        self.comboBox_FrecMuestreoON.setGeometry(QtCore.QRect(120, 20, 61, 25))
        self.comboBox_FrecMuestreoON.setStyleSheet(_fromUtf8("#comboBox_FrecMuestreoON{\n"
"    \n"
"    background-color: rgb(245, 245, 245);\n"
"}"))
        self.comboBox_FrecMuestreoON.setFrame(True)
        self.comboBox_FrecMuestreoON.setObjectName(_fromUtf8("comboBox_FrecMuestreoON"))
        self.comboBox_FrecMuestreoON.addItem(_fromUtf8(""))
        self.comboBox_FrecMuestreoON.addItem(_fromUtf8(""))
        self.comboBox_FrecMuestreoON.addItem(_fromUtf8(""))
        self.comboBox_FrecMuestreoON.addItem(_fromUtf8(""))
        self.comboBox_FrecMuestreoON.addItem(_fromUtf8(""))
        self.comboBox_FrecMuestreoON.addItem(_fromUtf8(""))
        self.comboBox_FrecMuestreoON.addItem(_fromUtf8(""))
        self.comboBox_FrecMuestreoON.addItem(_fromUtf8(""))
        self.comboBox_FrecMuestreoON.addItem(_fromUtf8(""))
        self.comboBox_FrecMuestreoON.addItem(_fromUtf8(""))
        self.comboBox_FrecMuestreoOFF.raise_()
        self.label.raise_()
        self.comboBox_FrecMuestreoON.raise_()
        self.label_FrecMuestreo.raise_()
        self.label_2.raise_()
        self.groupBox_FrecCorte.raise_()
        self.label_FrecMuestreo.raise_()
        self.label_2.raise_()
        self.groupBox_Filtro.raise_()
        self.groupBox_FrecMuestreo.raise_()
        self.tab_Preferencias.addTab(self.tab_FrecMuestreo, _fromUtf8(""))
        self.tab_Filtro = QtGui.QWidget()
        self.tab_Filtro.setObjectName(_fromUtf8("tab_Filtro"))
        self.groupBox_UnidadesAcelerometro = QtGui.QGroupBox(self.tab_Filtro)
        self.groupBox_UnidadesAcelerometro.setGeometry(QtCore.QRect(10, 20, 231, 81))
        self.groupBox_UnidadesAcelerometro.setObjectName(_fromUtf8("groupBox_UnidadesAcelerometro"))
        self.widget1 = QtGui.QWidget(self.groupBox_UnidadesAcelerometro)
        self.widget1.setGeometry(QtCore.QRect(15, 29, 158, 22))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_UnitsAcc = QtGui.QLabel(self.widget1)
        self.label_UnitsAcc.setObjectName(_fromUtf8("label_UnitsAcc"))
        self.gridLayout_3.addWidget(self.label_UnitsAcc, 0, 0, 1, 1)
        self.radioButton_gUnits = QtGui.QRadioButton(self.widget1)
        self.radioButton_gUnits.setChecked(True)
        self.radioButton_gUnits.setObjectName(_fromUtf8("radioButton_gUnits"))
        self.gridLayout_3.addWidget(self.radioButton_gUnits, 0, 1, 1, 1)
        self.radioButton_ms2Units = QtGui.QRadioButton(self.widget1)
        self.radioButton_ms2Units.setObjectName(_fromUtf8("radioButton_ms2Units"))
        self.gridLayout_3.addWidget(self.radioButton_ms2Units, 0, 2, 1, 1)
        self.tab_Preferencias.addTab(self.tab_Filtro, _fromUtf8(""))
        self.buttonBox = QtGui.QDialogButtonBox(Dialog_Filtro_Frecuencia)
        self.buttonBox.setGeometry(QtCore.QRect(80, 270, 181, 32))
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.label_FrecMuestreo.raise_()
        self.label_2.raise_()
        self.radioButton_filtroOn.raise_()
        self.radioButton_filtroOff.raise_()
        self.comboBox_FrecMuestreoON.raise_()
        self.comboBox_FrecMuestreoON.raise_()
        self.radioButton_filtroOn.raise_()
        self.radioButton_filtroOff.raise_()
        self.comboBox_FrecMuestreoON.raise_()
        self.tab_Preferencias.raise_()
        self.buttonBox.raise_()

        self.retranslateUi(Dialog_Filtro_Frecuencia)
        self.tab_Preferencias.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog_Filtro_Frecuencia.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog_Filtro_Frecuencia.reject)
        QtCore.QObject.connect(self.radioButton_filtroOn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.groupBox_FrecCorte.show)
        QtCore.QObject.connect(self.radioButton_filtroOff, QtCore.SIGNAL(_fromUtf8("clicked()")), self.groupBox_FrecCorte.hide)
        QtCore.QObject.connect(self.radioButton_filtroOff, QtCore.SIGNAL(_fromUtf8("clicked()")), self.comboBox_FrecMuestreoOFF.show)
        QtCore.QObject.connect(self.radioButton_filtroOn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.comboBox_FrecMuestreoOFF.hide)
        QtCore.QObject.connect(self.radioButton_filtroOn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.comboBox_FrecMuestreoON.show)
        QtCore.QObject.connect(self.radioButton_filtroOff, QtCore.SIGNAL(_fromUtf8("clicked()")), self.comboBox_FrecMuestreoON.hide)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Filtro_Frecuencia)

    def retranslateUi(self, Dialog_Filtro_Frecuencia):
        Dialog_Filtro_Frecuencia.setWindowTitle(_translate("Dialog_Filtro_Frecuencia", "Preferencias", None))
        self.label_FrecCorte.setText(_translate("Dialog_Filtro_Frecuencia", "Frecuencia de Corte", None))
        self.comboBox_FrecFiltroON.setItemText(0, _translate("Dialog_Filtro_Frecuencia", "5 Hz", None))
        self.comboBox_FrecFiltroON.setItemText(1, _translate("Dialog_Filtro_Frecuencia", "10 Hz", None))
        self.comboBox_FrecFiltroON.setItemText(2, _translate("Dialog_Filtro_Frecuencia", "21 Hz", None))
        self.comboBox_FrecFiltroON.setItemText(3, _translate("Dialog_Filtro_Frecuencia", "44 Hz", None))
        self.comboBox_FrecFiltroON.setItemText(4, _translate("Dialog_Filtro_Frecuencia", "94 Hz", None))
        self.comboBox_FrecFiltroON.setItemText(5, _translate("Dialog_Filtro_Frecuencia", "184 Hz", None))
        self.comboBox_FrecFiltroON.setItemText(6, _translate("Dialog_Filtro_Frecuencia", "260 Hz", None))
        self.groupBox_Filtro.setTitle(_translate("Dialog_Filtro_Frecuencia", "Filtro Pasa Baja", None))
        self.label_FiltroPasaBaja.setText(_translate("Dialog_Filtro_Frecuencia", "Filtro Pasa Baja:", None))
        self.radioButton_filtroOn.setText(_translate("Dialog_Filtro_Frecuencia", "On", None))
        self.radioButton_filtroOff.setText(_translate("Dialog_Filtro_Frecuencia", "Off", None))
        self.groupBox_FrecMuestreo.setTitle(_translate("Dialog_Filtro_Frecuencia", "Frecuencia Muestreo", None))
        self.label.setText(_translate("Dialog_Filtro_Frecuencia", "** Frec. Bajas sii El filtro pasa baja esta activado.", None))
        self.comboBox_FrecMuestreoOFF.setItemText(0, _translate("Dialog_Filtro_Frecuencia", "60", None))
        self.comboBox_FrecMuestreoOFF.setItemText(1, _translate("Dialog_Filtro_Frecuencia", "95", None))
        self.comboBox_FrecMuestreoOFF.setItemText(2, _translate("Dialog_Filtro_Frecuencia", "115", None))
        self.comboBox_FrecMuestreoOFF.setItemText(3, _translate("Dialog_Filtro_Frecuencia", "181", None))
        self.comboBox_FrecMuestreoOFF.setItemText(4, _translate("Dialog_Filtro_Frecuencia", "333", None))
        self.comboBox_FrecMuestreoOFF.setItemText(5, _translate("Dialog_Filtro_Frecuencia", "363", None))
        self.comboBox_FrecMuestreoOFF.setItemText(6, _translate("Dialog_Filtro_Frecuencia", "400", None))
        self.comboBox_FrecMuestreoOFF.setItemText(7, _translate("Dialog_Filtro_Frecuencia", "500", None))
        self.comboBox_FrecMuestreoOFF.setItemText(8, _translate("Dialog_Filtro_Frecuencia", "615", None))
        self.comboBox_FrecMuestreoOFF.setItemText(9, _translate("Dialog_Filtro_Frecuencia", "800", None))
        self.label_2.setText(_translate("Dialog_Filtro_Frecuencia", "**", None))
        self.label_FrecMuestreo.setText(_translate("Dialog_Filtro_Frecuencia", "Frec. Muestreo (Hz)", None))
        self.comboBox_FrecMuestreoON.setItemText(0, _translate("Dialog_Filtro_Frecuencia", "60", None))
        self.comboBox_FrecMuestreoON.setItemText(1, _translate("Dialog_Filtro_Frecuencia", "95", None))
        self.comboBox_FrecMuestreoON.setItemText(2, _translate("Dialog_Filtro_Frecuencia", "115", None))
        self.comboBox_FrecMuestreoON.setItemText(3, _translate("Dialog_Filtro_Frecuencia", "181", None))
        self.comboBox_FrecMuestreoON.setItemText(4, _translate("Dialog_Filtro_Frecuencia", "333", None))
        self.comboBox_FrecMuestreoON.setItemText(5, _translate("Dialog_Filtro_Frecuencia", "363", None))
        self.comboBox_FrecMuestreoON.setItemText(6, _translate("Dialog_Filtro_Frecuencia", "400", None))
        self.comboBox_FrecMuestreoON.setItemText(7, _translate("Dialog_Filtro_Frecuencia", "500", None))
        self.comboBox_FrecMuestreoON.setItemText(8, _translate("Dialog_Filtro_Frecuencia", "615", None))
        self.comboBox_FrecMuestreoON.setItemText(9, _translate("Dialog_Filtro_Frecuencia", "800", None))
        self.tab_Preferencias.setTabText(self.tab_Preferencias.indexOf(self.tab_FrecMuestreo), _translate("Dialog_Filtro_Frecuencia", "Frecuencias", None))
        self.groupBox_UnidadesAcelerometro.setTitle(_translate("Dialog_Filtro_Frecuencia", "Acelerómetro", None))
        self.label_UnitsAcc.setText(_translate("Dialog_Filtro_Frecuencia", "Unidades", None))
        self.radioButton_gUnits.setText(_translate("Dialog_Filtro_Frecuencia", "g", None))
        self.radioButton_ms2Units.setText(_translate("Dialog_Filtro_Frecuencia", "m/s2", None))
        self.tab_Preferencias.setTabText(self.tab_Preferencias.indexOf(self.tab_Filtro), _translate("Dialog_Filtro_Frecuencia", "Unidades", None))

