# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfazNodoCentral.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow_NodoCentral(object):
    def setupUi(self, MainWindow_NodoCentral):
        MainWindow_NodoCentral.setObjectName(_fromUtf8("MainWindow_NodoCentral"))
        MainWindow_NodoCentral.setEnabled(True)
        MainWindow_NodoCentral.resize(237, 390)
        font = QtGui.QFont()
        font.setKerning(True)
        MainWindow_NodoCentral.setFont(font)
        MainWindow_NodoCentral.setToolTip(_fromUtf8(""))
        MainWindow_NodoCentral.setStatusTip(_fromUtf8(""))
        MainWindow_NodoCentral.setAutoFillBackground(False)
        MainWindow_NodoCentral.setStyleSheet(_fromUtf8("#MainWindow_NodoCentral{\n"
"    \n"
"    background-color: rgb(227, 227, 227);\n"
"}"))
        self.centralwidget = QtGui.QWidget(MainWindow_NodoCentral)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 0, 221, 351))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 201, 321))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet(_fromUtf8("#groupBox{\n"
"    border: 1px solid gray;     \n"
"    background-color: rgb(249, 249, 249);\n"
"    border-radius: 3px; \n"
"}"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 10, 138, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(60, 30, 79, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.checkBox_FourierVisualizar = QtGui.QCheckBox(self.groupBox)
        self.checkBox_FourierVisualizar.setGeometry(QtCore.QRect(110, 280, 65, 20))
        self.checkBox_FourierVisualizar.setObjectName(_fromUtf8("checkBox_FourierVisualizar"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(15, 255, 161, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.checkBox_VibracionesVisualizar = QtGui.QCheckBox(self.groupBox)
        self.checkBox_VibracionesVisualizar.setGeometry(QtCore.QRect(16, 280, 88, 20))
        self.checkBox_VibracionesVisualizar.setObjectName(_fromUtf8("checkBox_VibracionesVisualizar"))
        self.horizontalSlider_Duracion = QtGui.QSlider(self.groupBox)
        self.horizontalSlider_Duracion.setGeometry(QtCore.QRect(20, 220, 160, 26))
        self.horizontalSlider_Duracion.setMinimum(1)
        self.horizontalSlider_Duracion.setMaximum(300)
        self.horizontalSlider_Duracion.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Duracion.setObjectName(_fromUtf8("horizontalSlider_Duracion"))
        self.label_Duracion = QtGui.QLabel(self.groupBox)
        self.label_Duracion.setGeometry(QtCore.QRect(120, 200, 48, 15))
        self.label_Duracion.setObjectName(_fromUtf8("label_Duracion"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(11, 200, 81, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(11, 120, 106, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.widget = QtGui.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(11, 144, 181, 50))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBox_EjeX = QtGui.QCheckBox(self.widget)
        self.checkBox_EjeX.setObjectName(_fromUtf8("checkBox_EjeX"))
        self.horizontalLayout_3.addWidget(self.checkBox_EjeX)
        self.checkBox_EjeY = QtGui.QCheckBox(self.widget)
        self.checkBox_EjeY.setObjectName(_fromUtf8("checkBox_EjeY"))
        self.horizontalLayout_3.addWidget(self.checkBox_EjeY)
        self.checkBox_EjeZ = QtGui.QCheckBox(self.widget)
        self.checkBox_EjeZ.setObjectName(_fromUtf8("checkBox_EjeZ"))
        self.horizontalLayout_3.addWidget(self.checkBox_EjeZ)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.checkBox_AccVector = QtGui.QCheckBox(self.widget)
        self.checkBox_AccVector.setObjectName(_fromUtf8("checkBox_AccVector"))
        self.verticalLayout_2.addWidget(self.checkBox_AccVector)
        self.widget1 = QtGui.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(13, 60, 121, 58))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.formLayout = QtGui.QFormLayout(self.widget1)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_2 = QtGui.QLabel(self.widget1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.comboBox_nombreNodo = QtGui.QComboBox(self.widget1)
        self.comboBox_nombreNodo.setObjectName(_fromUtf8("comboBox_nombreNodo"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox_nombreNodo)
        self.label_3 = QtGui.QLabel(self.widget1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.comboBox_nombreSensor = QtGui.QComboBox(self.widget1)
        self.comboBox_nombreSensor.setObjectName(_fromUtf8("comboBox_nombreSensor"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBox_nombreSensor)
        self.label.raise_()
        self.label_7.raise_()
        self.frame.raise_()
        self.checkBox_FourierVisualizar.raise_()
        self.label_5.raise_()
        self.checkBox_VibracionesVisualizar.raise_()
        self.horizontalSlider_Duracion.raise_()
        self.label_Duracion.raise_()
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(40, 336, 170, 31))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.pushButton_Detener = QtGui.QPushButton(self.splitter)
        self.pushButton_Detener.setObjectName(_fromUtf8("pushButton_Detener"))
        self.pushBut
        self.pushButton_Iniciar = QtGui.QPushButton(self.splitter)
        self.pushButton_Iniciar.setObjectName(_fromUtf8("pushButton_Iniciar"))
        self.frame.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.checkBox_VibracionesVisualizar.raise_()
        self.checkBox_FourierVisualizar.raise_()
        self.label_5.raise_()
        self.comboBox_nombreNodo.raise_()
        self.comboBox_nombreSensor.raise_()
        self.checkBox_VibracionesVisualizar.raise_()
        self.checkBox_FourierVisualizar.raise_()
        self.label_6.raise_()
        self.checkBox_EjeX.raise_()
        self.checkBox_EjeY.raise_()
        self.checkBox_EjeZ.raise_()
        self.checkBox_AccVector.raise_()
        self.pushButton_Iniciar.raise_()
        self.pushButton_Detener.raise_()
        self.pushButton_Iniciar.raise_()
        self.pushButton_Detener.raise_()
        self.pushButton_Detener.raise_()
        self.pushButton_Iniciar.raise_()
        self.pushButton_Detener.raise_()
        self.pushButton_Iniciar.raise_()
        self.splitter.raise_()
        MainWindow_NodoCentral.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow_NodoCentral)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 237, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuConfiguraci_n = QtGui.QMenu(self.menuBar)
        self.menuConfiguraci_n.setObjectName(_fromUtf8("menuConfiguraci_n"))
        MainWindow_NodoCentral.setMenuBar(self.menuBar)
        self.actionSensor_Preferencias = QtGui.QAction(MainWindow_NodoCentral)
        self.actionSensor_Preferencias.setObjectName(_fromUtf8("actionSensor_Preferencias"))
        self.actionSensor = QtGui.QAction(MainWindow_NodoCentral)
        self.actionSensor.setObjectName(_fromUtf8("actionSensor"))
        self.menuConfiguraci_n.addAction(self.actionSensor_Preferencias)
        self.menuBar.addAction(self.menuConfiguraci_n.menuAction())

        self.retranslateUi(MainWindow_NodoCentral)
        QtCore.QObject.connect(self.pushButton_Detener, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pushButton_Iniciar.animateClick)
        QtCore.QObject.connect(self.horizontalSlider_Duracion, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.label_Duracion.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_NodoCentral)

    def retranslateUi(self, MainWindow_NodoCentral):
        MainWindow_NodoCentral.setWindowTitle(_translate("MainWindow_NodoCentral", "E-Bridge System", None))
        self.label.setText(_translate("MainWindow_NodoCentral", "Sistema Monitoreo", None))
        self.label_7.setText(_translate("MainWindow_NodoCentral", "E-Bridge", None))
        self.checkBox_FourierVisualizar.setText(_translate("MainWindow_NodoCentral", "Fourier", None))
        self.label_5.setText(_translate("MainWindow_NodoCentral", "Visualizar:", None))
        self.checkBox_VibracionesVisualizar.setText(_translate("MainWindow_NodoCentral", "Vibraciones", None))
        self.label_Duracion.setText(_translate("MainWindow_NodoCentral", "1", None))
        self.label_6.setText(_translate("MainWindow_NodoCentral", "Duración (min):", None))
        self.label_4.setText(_translate("MainWindow_NodoCentral", "Datos a Visualizar", None))
        self.checkBox_EjeX.setText(_translate("MainWindow_NodoCentral", "Eje X", None))
        self.checkBox_EjeY.setText(_translate("MainWindow_NodoCentral", "Eje Y", None))
        self.checkBox_EjeZ.setText(_translate("MainWindow_NodoCentral", "Eje Z", None))
        self.checkBox_AccVector.setText(_translate("MainWindow_NodoCentral", "Vector Acc", None))
        self.label_2.setText(_translate("MainWindow_NodoCentral", "Nodo:", None))
        self.label_3.setText(_translate("MainWindow_NodoCentral", "Sensor:", None))
        self.pushButton_Detener.setText(_translate("MainWindow_NodoCentral", "Detener", None))
        self.pushButton_Iniciar.setText(_translate("MainWindow_NodoCentral", "Iniciar", None))
        self.menuConfiguraci_n.setTitle(_translate("MainWindow_NodoCentral", "Configuración", None))
        self.actionSensor_Preferencias.setText(_translate("MainWindow_NodoCentral", "Preferencias", None))
        self.actionSensor.setText(_translate("MainWindow_NodoCentral", "sensor", None))

